use sakila;
select * from actor;
alter table actor add firstlast varchar(255);
describe actor;
select concat(first_name, ' ', last_name) as ' Actor Name' from actor;
select actor_id, first_name, last_name from actor where first_name='JOE';
select actor_id, first_name, last_name from actor where last_name like '%GEN';
select actor_id, first_name, last_name from actor where last_name like '%LI%' order by last_name, first_name;
select country_id, country from country where country in ('Afganistan', 'Bangladesh', 'China');
describe actor;
alter table actor add column description blob after last_name;
describe actor;
alter table actor drop column description;
describe actor;
select last_name, count(*) as 'count' from actor group by last_name;
select last_name, count(*) as 'count' from actor group by last_name having count>2;
update actor set first_name = 'HARPO' where first_name = 'GROUCHO' and last_name='WILLIAMS';
update actor set first_name = 'GROUCHO' where first_name = 'HARPO' and last_name='WILLIAMS';
describe sakila.address;
describe staff;
select s.first_name, s.last_name, a.address from staff s left join address a on s.address_id = a.address_id;
describe address;
describe payment;
describe staff;
select first_name, last_name, SUM(amount) from staff s inner join payment p on s.staff_id = p.staff_id  
group by p.staff_id;
desc film;
desc film_actor;
select title, count(actor_id) from film f inner join film_actor fa on f.film_id=fa.film_id group by title;
select title, count(title) from film f inner join film_actor fa on f.film_id=fa.film_id group by title;
desc film;
select title, count(title) from film f inner join film_actor fa on f.film_id=fa.film_id where title='HUNCHBACK IMPOSSIBLE';
desc customer;
select first_name, last_name, SUM(amount) from payment p inner join customer c on p.customer_id = c.customer_id  
group by p.customer_id order by last_name ASC;
select title from film where (title like 'K%' or title like 'Q%') and language_id=(select language_id from language where name='English');
desc actor;
select first_name, last_name from actor where actor_id in (select actor_id from film_actor where film_id in (select film_id from film where title='ALONE TRIP'));
select first_name, last_name, email from customer cu join address a on (cu.address_id = a.address_id) join city cit on (a.city_id=cit.city_id) join country cntry on (cit.country_id=cntry.country_id);
desc customer; 
desc film;
select title from film where rating = 'G';
select title from film f join film_category fcat on (f.film_id=fcat.film_id) join category c on (fcat.category_id=c.category_id); 
alter table film add column all_rented_movies int after title;
desc film;
select title, count(f.film_id) as 'all_rented_movies' from film f join inventory i on (f.film_id=i.film_id) join rental r on (i.inventory_id = r.inventory_id) group by title order by all_rented_movies DESC;  
select s.store_id, sum(p.amount) from payment p join staff s on (p.staff_id=s.staff_id) group by store_id;
desc store; 
desc address;
select store_id, city, country from store s join address a on (s.address_id=a.address_id) join city c on (a.city_id=c.city_id) join country cntry on (c.country_id=cntry.country_id);
select c.name as "top 5", sum(p.amount) as "gross" from category c join film_category fc on (c.category_id=fc.category_id) join inventory i on (fc.film_id=i.film_id) join rental r on (i.inventory_id=r.inventory_id) join payment p on (r.rental_id=p.rental_id) group by c.name order by gross DESC limit 5;
desc category;
desc film_category;
desc inventory;
desc rental;
desc payment;
drop view topfive;
create view topfive as select c.name as "top 5", sum(p.amount) as "gross" from category as c join film_category as fc on (c.category_id = fc.category_id) join inventory as i on (fc.film_id=i.film_id) join rental as r on (i.inventory_id=r.inventory_id) join payment as p on (r.rental_id=p.rental_id) group by c.name order by gross DESC limit 5;
desc topfive;
select * from topfive;